// Bundle Vercel functions เป็นไฟล์เดียว (esbuild มากับ vite อยู่แล้ว)
// เหตุผล: Vercel Node builder ไม่ bundle relative import ข้ามโฟลเดอร์เมื่อ package เป็น ESM
import { build } from "esbuild";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { execSync } from "node:child_process";

await mkdir("api", { recursive: true });
// สร้าง demo.db แล้วฝังเป็น base64 ใน bundle เลย — ไม่พึ่ง includeFiles ของ Vercel
execSync("npm run build:demo-db", { stdio: "inherit" });
const demoDb = await readFile("demo.db");
await writeFile(
  "vercel-adapter/demo-db.generated.mjs",
  `// generated by scripts/build-api.mjs — do not edit
export const demoDbBase64 = ${JSON.stringify(demoDb.toString("base64"))};
`,
);
const shared = {
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node20",
  // native/runtime deps ให้ Vercel ติดตั้งเองผ่าน node_modules (nft ตามให้)
  external: ["@libsql/client", "@vercel/functions"],
};
await build({ ...shared, entryPoints: ["vercel-adapter/handlers/catchall.ts"], outfile: "api/index.mjs" });
await build({ ...shared, entryPoints: ["vercel-adapter/handlers/cron.ts"], outfile: "api/cron.mjs" });
console.log("bundled api/index.mjs + api/cron.mjs");
